"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WS_SEND_MESSAGE_RATE_LIMIT = exports.WSS_URL = exports.HTTPS_URL_V2 = exports.HTTPS_URL = exports.SONAR_BUILD = exports.SONAR_VERSION = exports.API_DOMAIN = void 0;
exports.API_DOMAIN = 'live.sonar.app';
exports.SONAR_VERSION = '1.4';
exports.SONAR_BUILD = 56;
exports.HTTPS_URL = `https://${exports.API_DOMAIN}/v1`;
exports.HTTPS_URL_V2 = `https://${exports.API_DOMAIN}/v2`;
exports.WSS_URL = `wss://${exports.API_DOMAIN}/v2`;
exports.WS_SEND_MESSAGE_RATE_LIMIT = 275;
